security:
    role_hierarchy:
        ROLE_TODOS:  [ROLE_TODOS]
        ROLE_ROOT:   [ROLE_TODOS, ROLE_ADMIN, ROLE_PERS]

    encoders:
        Isi\SesionBundle\Entity\Usuarios: 
            algorithm: md5
            encode_as_base64: false
            iterations: 1

    providers:
        main:
            entity: { class: Isi\SesionBundle\Entity\Usuarios, property: username}

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: isi_sesion_homepage
                username_parameter: form[username]
                password_parameter: form[password]
                remember_me: true
            logout:
                path: /logout
                target: /login

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bienvenida, roles: [ROLE_TODOS] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/siale, roles: [ROLE_SIALE] }
        - { path: ^/configuracion, roles: [ROLE_CONFIG] }
        - { path: ^/persona, roles: [ROLE_PERS] }
