parameters:
    isi_mensaje.clase: Isi\AdminBundle\Controller\MensajesSistemaController
    isi_id.bd: $id

services:
    isi_mensaje:
        class: "%isi_mensaje.clase%"
        arguments: ["%isi_id.bd%"]

# "@doctrine.orm.entity_manager",
