parameters:
    isi_mensaje.clase: Isi\AdminBundle\Mensajes
    isi_id.bd: $id

services:
    isi_mensaje:
        class: "%isi_mensaje.clase%"
        arguments: ["@doctrine.orm.entity_manager", "%isi_id.bd%"]
