<?php

namespace Isi\PersonaBundle\Repository;

/**
 * CabGrSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabGrSocialesRepository extends \Doctrine\ORM\EntityRepository
{
}
