<?php

namespace Isi\PersonaBundle\Repository;

/**
 * DniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DniesRepository extends \Doctrine\ORM\EntityRepository
{
}
