<?php

namespace Isi\PersonaBundle\Repository;

/**
 * EstCivilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstCivilesRepository extends \Doctrine\ORM\EntityRepository
{
}
