<?php

namespace Isi\PersonaBundle\Repository;

/**
 * FtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtsRepository extends \Doctrine\ORM\EntityRepository
{
}
