<?php

namespace Isi\PersonaBundle\Repository;

/**
 * LugarNacimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarNacimRepository extends \Doctrine\ORM\EntityRepository
{
}
