isi_sesion_homepage:
    path:     /mi/inicio/
    defaults: { _controller: IsiSesionBundle:Default:index }

login:
    path: /login
    defaults: { _controller: IsiSesionBundle:Default:login}

isi_sesion_actuAvatar:
    path: /actuAvatar/{usuario}
    defaults: { _controller: IsiSesionBundle:Default:actuAvatar, usuario: ""}

isi_sesion_usrA:
    path: /usuario/crear
    defaults: { _controller: IsiSesionBundle:Default:nuevo}
