isi_sesion_homepage:
    path:     /mi/inicio/
    defaults: { _controller: IsiSesionBundle:Default:index }

login:
    path: /login
    defaults: { _controller: IsiSesionBundle:Default:login }

isi_sesion_actuAvatar:
    path: /actuAvatar/{usuario}
    defaults: { _controller: IsiSesionBundle:Default:actuAvatar, usuario: "" }

isi_sesion_usrA:
    path: /admin/usuario/crear/{id}
    defaults: { _controller: IsiSesionBundle:Default:nuevo, id: 0 }

isi_sesion_usrL:
    path: /admin/usuario
    defaults: { _controller: IsiSesionBundle:Default:listado }

isi_sesion_usrM:
    path: /admin/usuario/edicion/{id}
    defaults: { _controller: IsiSesionBundle:Default:edicion }

isi_sesion_usrMUsr:
    path: /mi/inicio/preferencias
    defaults: { _controller: IsiSesionBundle:Default:preferencias }
