<?php

namespace Isi\PersonalBundle\Repository;

/**
 * LugarTrabajoPersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarTrabajoPersRepository extends \Doctrine\ORM\EntityRepository
{
}
