isi_persona_homepage:
    path:     /
    defaults: { _controller: IsiPersonaBundle:Default:index }

isi_persona_A:
    path:     /nueva
    defaults: { _controller: IsiPersonaBundle:Default:nueva }

isi_persona_C:
    path:     /consulta
    defaults: { _controller: IsiPersonaBundle:Default:buscarPers }

isi_persona_M:
    path:     /edicion/{id}
    defaults: { _controller: IsiPersonaBundle:Default:edicion }

isi_persona_selTrab:
    path:     /guardar/seleccion/{id}
    defaults: { _controller: IsiPersonaBundle:Default:guardaSeleccion, id: '' }
