isi_persona_homepage:
    path:     /
    defaults: { _controller: IsiPersonaBundle:Default:index }

isi_persona_estadoCivil:
    path:     /estCivil
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:index }
