isi_persona_homepage:
    path:     /
    defaults: { _controller: IsiPersonaBundle:Default:index }

isi_persona_estadoCivil:
    path:     /estCivil
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:index }

isi_persona_identGenero:
    path:     /identGenero
    defaults: { _controller: IsiPersonaBundle:IdentidadGenero:index }

isi_persona_lugarNacim:
    path:     /lugarNacim
    defaults: { _controller: IsiPersonaBundle:LugarNacimiento:index }

isi_persona_nueva:
    path:     /nueva
    defaults: { _controller: IsiPersonaBundle:Default:nueva }
