isi_persona_homepage:
    path:     /
    defaults: { _controller: IsiPersonaBundle:Default:index }

isi_persona_A:
    path:     /nueva
    defaults: { _controller: IsiPersonaBundle:Default:nueva }

isi_persona_C:
    path:     /consulta
    defaults: { _controller: IsiPersonaBundle:Default:buscarPers }

isi_persona_M:
    path:     /edicion/{id}
    defaults: { _controller: IsiPersonaBundle:Default:edicion }

isi_persona_ABMSelPers:
    path:     /guardar/seleccion/personas/{idsCodi}
    defaults: { _controller: IsiPersonaBundle:Default:guardaSeleccionPers, idsCodi: '' }

isi_persona_BSelPers:
    path:     /quitar/seleccion/personas/{id}
    defaults: { _controller: IsiPersonaBundle:Default:eliminarUnaPersSeleccion}
