parameters:
    isi_F3Persona.clase: Isi\PersonaBundle\F3Persona
    isi_textoABuscar: $texto

services:
    isi_buscarPers:
        class: "%isi_F3Persona.clase%"
        arguments: ["@doctrine.orm.entity_manager", "%isi_textoABuscar%"]
