isi_config_homepage:
    path:     /
    defaults: { _controller: IsiConfigBundle:Default:index }

isi_config_estadoCivilNuevo:
    path:     /estCivil/nuevo
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:nuevo }

isi_config_estadoCivilFormulario:
    path:     /estCivil/formulario
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:formulario }

isi_config_estadoCivilEdicion:
    path:     /estCivil/edicion/{id}
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:edicion }
    requirements:
        id:  \d+

isi_config_estadoCivilBorrar:
    path:     /estCivil/borrar/{id}
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:borrar, id: 0}
    requirements:
        id:  \d+

isi_config_identGeneroNuevo:
    path:     /identGenero/nuevo
    defaults: { _controller: IsiPersonaBundle:IdentidadGenero:nuevo }

isi_config_identGeneroEdicion:
    path:     /identGenero/edicion/{id}
    defaults: { _controller: IsiPersonaBundle:IdentidadGenero:edicion }
    # requirements:
    #     id:  \d+

isi_config_identGeneroBorrar:
    path:     /identGenero/borrar/{id}
    defaults: { _controller: IsiPersonaBundle:IdentidadGenero:borrar, id: 0}
    # requirements:
    #     id:  \d+

isi_config_lugarNacimNuevo:
    path:     /lugNacim/nuevo
    defaults: { _controller: IsiPersonaBundle:LugarNacimiento:nuevo }

isi_config_lugarNacimEdicion:
    path:     /lugNacim/edicion/{id}
    defaults: { _controller: IsiPersonaBundle:LugarNacimiento:edicion }
    requirements:
        id:  \d+

isi_config_lugarNacimBorrar:
    path:     /lugNacim/borrar/{id}
    defaults: { _controller: IsiPersonaBundle:LugarNacimiento:borrar, id: 0}
    requirements:
        id:  \d+

isi_config_personaNueva:
        path:     /persona/nueva
        defaults: { _controller: IsiPersonaBundle:Default:nueva }
