isi_config_homepage:
    path:     /
    defaults: { _controller: IsiConfigBundle:Default:index }

isi_config_estadoCivil:
    path:     /estCivil
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:index }

isi_config_estadoCivilNuevo:
    path:     /estCivil/nuevo
    defaults: { _controller: IsiPersonaBundle:EstadoCivil:nuevo }
