isi_config_homepage:
    path:     /
    defaults: { _controller: IsiConfigBundle:Default:index }

# isi_persona_estadoCivil:
isi_config_estCiv:
    path:     /estadoCivil
    defaults: { _controller: IsiConfigBundle:EstadoCivil:index }

isi_config_estCivA:
    path:     /estadoCivil/nuevo
    defaults: { _controller: IsiConfigBundle:EstadoCivil:nuevo }

isi_config_estCivForm:
    path:     /estadoCivil/formulario
    defaults: { _controller: IsiConfigBundle:EstadoCivil:formulario }

isi_config_estCivM:
    path:     /estadoCivil/edicion/{id}
    defaults: { _controller: IsiConfigBundle:EstadoCivil:edicion }

isi_config_estCivB:
    path:     /estadoCivil/borrar/{id}
    defaults: { _controller: IsiConfigBundle:EstadoCivil:borrar, id: 0 }

isi_config_identGenero:
    path:     /identidadDeGenero
    defaults: { _controller: IsiConfigBundle:IdentidadGenero:index }

isi_config_identGeneroA:
    path:     /identidadDeGenero/nuevo
    defaults: { _controller: IsiConfigBundle:IdentidadGenero:nuevo }

isi_config_identGeneroM:
    path:     /identidadDeGenero/edicion/{id}
    defaults: { _controller: IsiConfigBundle:IdentidadGenero:edicion }

isi_config_identGeneroB:
    path:     /identidadDeGenero/borrar/{id}
    defaults: { _controller: IsiConfigBundle:IdentidadGenero:borrar, id: 0 }

isi_config_lugNacim:
    path:     /lugarDeNacimiento
    defaults: { _controller: IsiConfigBundle:LugarNacimiento:index }

isi_config_lugNacimA:
    path:     /lugarDeNacimiento/nuevo
    defaults: { _controller: IsiConfigBundle:LugarNacimiento:nuevo }

isi_config_lugNacimM:
    path:     /lugarDeNacimiento/edicion/{id}
    defaults: { _controller: IsiConfigBundle:LugarNacimiento:edicion }

isi_config_lugNacimB:
    path:     /lugarDeNacimiento/borrar/{id}
    defaults: { _controller: IsiConfigBundle:LugarNacimiento:borrar, id: 0 }

isi_config_grupoSoc:
    path:     /TipoGSocial
    defaults: { _controller: IsiConfigBundle:TiposGrSociales:index }

isi_config_grupoSocA:
    path:     /TipoGSocial/nuevo
    defaults: { _controller: IsiConfigBundle:TiposGrSociales:nuevo }

isi_config_grupoSocM:
    path:     /TipoGSocial/edicion/{id}
    defaults: { _controller: IsiConfigBundle:TiposGrSociales:edicion }

isi_config_grupoSocB:
    path:     /TipoGSocial/borrar/{id}
    defaults: { _controller: IsiConfigBundle:TiposGrSociales:borrar, id: 0 }

isi_config_tipoLugTrab:
    path:     /TipoLugTrab
    defaults: { _controller: IsiConfigBundle:TiposLugarTrabajo:index }

isi_config_tipoLugTrabA:
    path:     /TipoLugTrab/nuevo
    defaults: { _controller: IsiConfigBundle:TiposLugarTrabajo:nuevo }

isi_config_tipoLugTrabM:
    path:     /TipoLugTrab/edicion/{id}
    defaults: { _controller: IsiConfigBundle:TiposLugarTrabajo:edicion }

isi_config_tipoLugTrabB:
    path:     /TipoLugTrab/borrar/{id}
    defaults: { _controller: IsiConfigBundle:TiposLugarTrabajo:borrar, id: 0 }

isi_config_lugTrab:
    path:     /LugTrab
    defaults: { _controller: IsiConfigBundle:LugarTrabajo:index }

isi_config_lugTrabA:
    path:     /LugTrab/nuevo
    defaults: { _controller: IsiConfigBundle:LugarTrabajo:nuevo }

isi_config_lugTrabM:
    path:     /LugTrab/edicion/{id}
    defaults: { _controller: IsiConfigBundle:LugarTrabajo:edicion }

isi_config_lugTrabB:
    path:     /LugTrab/borrar/{id}
    defaults: { _controller: IsiConfigBundle:LugarTrabajo:borrar, id: 0 }

isi_config_lugTrabPers:
        path:     /LugarTrabPersonas
        defaults: { _controller: IsiConfigBundle:LugarTrabajoPersonas:index }
