<?php

namespace Isi\ConfigBundle\Repository;

/**
 * EstCivilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstCivilesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrdByDescrip()
    {
        return $this->getEntityManager() ->createQuery(
            "SELECT e FROM IsiConfigBundle:EstCiviles e ORDER BY e.descrip ASC"
        )->getResult();
    }
 }
