<?php

namespace Isi\ConfigBundle\Repository;

/**
 * GrupoSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoSocialesRepository extends \Doctrine\ORM\EntityRepository
{
}
