<?php

namespace Isi\ConfigBundle\Repository;

/**
 * IdentGenerosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentGenerosRepository extends \Doctrine\ORM\EntityRepository
{
}
