<?php

namespace Isi\ConfigBundle\Repository;

/**
 * LugarTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
