<?php

namespace Isi\ConfigBundle\Repository;

/**
 * MensajesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajesRepository extends \Doctrine\ORM\EntityRepository
{
}
