<?php

namespace Isi\ConfigBundle\Repository;

/**
 * TiposMensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposMensajeRepository extends \Doctrine\ORM\EntityRepository
{
}
