<?php

namespace Isi\ConfigBundle\Repository;

/**
 * TipoLugarTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoLugarTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
