<?php

namespace Isi\ConfigBundle\Repository;

/**
 * TiposLugarTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposLugarTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
