<?php

namespace Isi\ConfigBundle\Repository;

/**
 * TiposGrSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposGrSocialesRepository extends \Doctrine\ORM\EntityRepository
{
}
