isi_personal_homepage:
    path:     /
    defaults: { _controller: IsiPersonalBundle:Default:index}

isi_personal_oficinas:
    path:     /horariooficinas/{ids}
    defaults: { _controller: IsiPersonalBundle:Default:horarioOficinas, ids: '' }
