isi_personal_homepage:
    path:     /
    defaults: { _controller: IsiPersonalBundle:Default:index}

isi_personal_oficinas:
    path:     /oficinas/{ids}
    defaults: { _controller: IsiPersonalBundle:Default:oficinas, ids: '' }
