isi_personal_homepage:
    path:     /
    defaults: { _controller: IsiPersonalBundle:Default:index }

isi_personal_oficinas:
    path:     /oficinas
    defaults: { _controller: IsiPersonalBundle:Default:oficinas }
